sudo: false

addons:
  apt:
    packages:
      - xvfb
      - libsecret-1-0

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - npm install
  - npm run vscode:prepublish

script:
  - npm test
  - npm run coverage
